-- MySQL Script generated by MySQL Workbench
-- Thu Aug 30 11:29:45 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema TED
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `TED` ;

-- -----------------------------------------------------
-- Schema TED
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TED` DEFAULT CHARACTER SET utf8 ;
USE `TED` ;

-- -----------------------------------------------------
-- Table `TED`.`Profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TED`.`Profile` ;

CREATE TABLE IF NOT EXISTS `TED`.`Profile` (
  `ProfileID` INT NOT NULL,
  `Name` VARCHAR(50) NOT NULL,
  `Surname` VARCHAR(70) NOT NULL,
  `Age` INT NULL,
  `Address` VARCHAR(100) NULL,
  `Telephone` VARCHAR(20) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `WorkHistory` TEXT(2000) NULL,
  `ReasearchTraining` TEXT(2000) NULL,
  `Education` TEXT(2000) NULL,
  `ProfQual` TEXT(2000) NULL,
  `Computer` TEXT(1000) NULL,
  `OtherInfo` TEXT(2000) NULL,
  `Interests` TEXT(2000) NULL,
  `AgeR` INT NULL,
  `AddressR` INT NULL,
  `TelephoneR` INT NULL,
  `EmailR` INT NULL,
  `WorkHistoryR` INT NULL,
  `ReTrainR` INT NULL,
  `EducationR` INT NULL,
  `ProfQualR` INT NULL,
  `OtherInfoR` INT NULL,
  `InterestR` INT NULL,
  `ComputerR` INT NULL,
  PRIMARY KEY (`ProfileID`),
  UNIQUE INDEX `ProfileID_UNIQUE` (`ProfileID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TED`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TED`.`User` ;

CREATE TABLE IF NOT EXISTS `TED`.`User` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(100) NOT NULL,
  `Password` VARCHAR(50) NOT NULL,
  `Name` VARCHAR(50) NOT NULL,
  `Surname` VARCHAR(70) NOT NULL,
  `Telephone` VARCHAR(20) NOT NULL,
  `Photo` VARCHAR(250) NULL,
  `ProfileID` INT NOT NULL,
  UNIQUE INDEX `User_id_UNIQUE` (`UserID` ASC),
  PRIMARY KEY (`UserID`),
  INDEX `fk_User_Profile_idx` (`ProfileID` ASC),
  UNIQUE INDEX `Profile_ProfileID_UNIQUE` (`ProfileID` ASC),
  CONSTRAINT `fk_User_Profile`
    FOREIGN KEY (`ProfileID`)
    REFERENCES `TED`.`Profile` (`ProfileID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TED`.`Friends`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TED`.`Friends` ;

CREATE TABLE IF NOT EXISTS `TED`.`Friends` (
  `FriendID` INT NOT NULL,
  `User1` INT NOT NULL,
  `User2` INT NOT NULL,
  `RequestStatus` INT NULL,
  PRIMARY KEY (`FriendID`),
  INDEX `fk_Friends_User1_idx` (`User1` ASC),
  INDEX `fk_Friends_User2_idx` (`User2` ASC),
  UNIQUE INDEX `FriendID_UNIQUE` (`FriendID` ASC),
  CONSTRAINT `fk_Friends_User1`
    FOREIGN KEY (`User1`)
    REFERENCES `TED`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Friends_User2`
    FOREIGN KEY (`User2`)
    REFERENCES `TED`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TED`.`Articles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TED`.`Articles` ;

CREATE TABLE IF NOT EXISTS `TED`.`Articles` (
  `idArticles` INT NOT NULL,
  `Text` VARCHAR(1000) NULL,
  `Image` VARCHAR(200) NULL,
  `Video` VARCHAR(200) NULL,
  `UserID` INT NOT NULL,
  PRIMARY KEY (`idArticles`),
  UNIQUE INDEX `idArticles_UNIQUE` (`idArticles` ASC),
  INDEX `fk_Articles_User1_idx` (`UserID` ASC),
  CONSTRAINT `fk_Articles_User1`
    FOREIGN KEY (`UserID`)
    REFERENCES `TED`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TED`.`ArticleLikes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TED`.`ArticleLikes` ;

CREATE TABLE IF NOT EXISTS `TED`.`ArticleLikes` (
  `idArticleLikes` INT NOT NULL,
  `ArticleID` INT NOT NULL,
  `UserID` INT NOT NULL,
  PRIMARY KEY (`idArticleLikes`),
  UNIQUE INDEX `idArticleLikes_UNIQUE` (`idArticleLikes` ASC),
  INDEX `fk_ArticleLikes_Articles1_idx` (`ArticleID` ASC),
  INDEX `fk_ArticleLikes_User1_idx` (`UserID` ASC),
  CONSTRAINT `fk_ArticleLikes_Articles1`
    FOREIGN KEY (`ArticleID`)
    REFERENCES `TED`.`Articles` (`idArticles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ArticleLikes_User1`
    FOREIGN KEY (`UserID`)
    REFERENCES `TED`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `TED`.`Profile`
-- -----------------------------------------------------
START TRANSACTION;
USE `TED`;
INSERT INTO `TED`.`Profile` (`ProfileID`, `Name`, `Surname`, `Age`, `Address`, `Telephone`, `Email`, `WorkHistory`, `ReasearchTraining`, `Education`, `ProfQual`, `Computer`, `OtherInfo`, `Interests`, `AgeR`, `AddressR`, `TelephoneR`, `EmailR`, `WorkHistoryR`, `ReTrainR`, `EducationR`, `ProfQualR`, `OtherInfoR`, `InterestR`, `ComputerR`) VALUES (1, 'Administrator', 'AdminSurname', 20, 'Admin Home 25', '1234', 'admin@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `TED`.`Profile` (`ProfileID`, `Name`, `Surname`, `Age`, `Address`, `Telephone`, `Email`, `WorkHistory`, `ReasearchTraining`, `Education`, `ProfQual`, `Computer`, `OtherInfo`, `Interests`, `AgeR`, `AddressR`, `TelephoneR`, `EmailR`, `WorkHistoryR`, `ReTrainR`, `EducationR`, `ProfQualR`, `OtherInfoR`, `InterestR`, `ComputerR`) VALUES (2, 'AB', 'Basilopoulos', 55, 'kaisarianhs 35', '2462456256', 'ab@hotmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `TED`.`Profile` (`ProfileID`, `Name`, `Surname`, `Age`, `Address`, `Telephone`, `Email`, `WorkHistory`, `ReasearchTraining`, `Education`, `ProfQual`, `Computer`, `OtherInfo`, `Interests`, `AgeR`, `AddressR`, `TelephoneR`, `EmailR`, `WorkHistoryR`, `ReTrainR`, `EducationR`, `ProfQualR`, `OtherInfoR`, `InterestR`, `ComputerR`) VALUES (3, 'Stylianos', 'Sirtagias', 22, 'Lamia 21', '13523452345', 'stelios@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `TED`.`Profile` (`ProfileID`, `Name`, `Surname`, `Age`, `Address`, `Telephone`, `Email`, `WorkHistory`, `ReasearchTraining`, `Education`, `ProfQual`, `Computer`, `OtherInfo`, `Interests`, `AgeR`, `AddressR`, `TelephoneR`, `EmailR`, `WorkHistoryR`, `ReTrainR`, `EducationR`, `ProfQualR`, `OtherInfoR`, `InterestR`, `ComputerR`) VALUES (4, 'Litsa', 'Elaxana', 21, 'Flufada 56', '2134234', 'litsa@yahoo.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `TED`.`Profile` (`ProfileID`, `Name`, `Surname`, `Age`, `Address`, `Telephone`, `Email`, `WorkHistory`, `ReasearchTraining`, `Education`, `ProfQual`, `Computer`, `OtherInfo`, `Interests`, `AgeR`, `AddressR`, `TelephoneR`, `EmailR`, `WorkHistoryR`, `ReTrainR`, `EducationR`, `ProfQualR`, `OtherInfoR`, `InterestR`, `ComputerR`) VALUES (5, 'AEK', 'AEK', 90, 'Nea Filadelfeia', '123234', 'aek1924@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `TED`.`Profile` (`ProfileID`, `Name`, `Surname`, `Age`, `Address`, `Telephone`, `Email`, `WorkHistory`, `ReasearchTraining`, `Education`, `ProfQual`, `Computer`, `OtherInfo`, `Interests`, `AgeR`, `AddressR`, `TelephoneR`, `EmailR`, `WorkHistoryR`, `ReTrainR`, `EducationR`, `ProfQualR`, `OtherInfoR`, `InterestR`, `ComputerR`) VALUES (6, 'Stamaths', 'Gardelhs', 50, 'Zwgrafou', '634564', 'gardelis1980@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `TED`.`Profile` (`ProfileID`, `Name`, `Surname`, `Age`, `Address`, `Telephone`, `Email`, `WorkHistory`, `ReasearchTraining`, `Education`, `ProfQual`, `Computer`, `OtherInfo`, `Interests`, `AgeR`, `AddressR`, `TelephoneR`, `EmailR`, `WorkHistoryR`, `ReTrainR`, `EducationR`, `ProfQualR`, `OtherInfoR`, `InterestR`, `ComputerR`) VALUES (7, 'Jimmy', 'Page', 55, 'London', '23412341', 'ledzep@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `TED`.`User`
-- -----------------------------------------------------
START TRANSACTION;
USE `TED`;
INSERT INTO `TED`.`User` (`UserID`, `Email`, `Password`, `Name`, `Surname`, `Telephone`, `Photo`, `ProfileID`) VALUES (1, 'admin@gmail.com', '123', 'adminNam', 'adminSurnam', '1513454135', 'Ottawa[1].jpg', 1);
INSERT INTO `TED`.`User` (`UserID`, `Email`, `Password`, `Name`, `Surname`, `Telephone`, `Photo`, `ProfileID`) VALUES (2, 'ab@hotmail.com', '345', 'ab', 'basilopoulos', '3456245624', 'generic_image_missing-profile.jpg', 2);
INSERT INTO `TED`.`User` (`UserID`, `Email`, `Password`, `Name`, `Surname`, `Telephone`, `Photo`, `ProfileID`) VALUES (3, 'stelios@gmail.com', 's135', 'stelios', 'sirtagias', '45684568', 'generic_image_missing-profile.jpg', 3);
INSERT INTO `TED`.`User` (`UserID`, `Email`, `Password`, `Name`, `Surname`, `Telephone`, `Photo`, `ProfileID`) VALUES (4, 'litsa@yahoo.com', '012', 'litsa', 'ela3ana', '2451246', 'generic_image_missing-profile.jpg', 4);
INSERT INTO `TED`.`User` (`UserID`, `Email`, `Password`, `Name`, `Surname`, `Telephone`, `Photo`, `ProfileID`) VALUES (5, 'aek1924@gmail.com', '1924', 'aek', 'aek', '6971924', 'dc49af625453a85ffa52cb31d65d520a_499662.jpg', 5);
INSERT INTO `TED`.`User` (`UserID`, `Email`, `Password`, `Name`, `Surname`, `Telephone`, `Photo`, `ProfileID`) VALUES (6, 'gardelis1980@gmail.com', '1980', 'stamatis', 'gardelis', '294624936', 'hqdefault.jpg', 6);
INSERT INTO `TED`.`User` (`UserID`, `Email`, `Password`, `Name`, `Surname`, `Telephone`, `Photo`, `ProfileID`) VALUES (7, 'ledzep@gmail.com', '1971', 'led', 'zeppelin', '573736736', NULL, 7);

COMMIT;

